### ISSUE TITLE
Modelling Multiple Strains

### ISSUE THREAD

**Issue by roberthinch** [BDI-pathogens/OpenABM-Covid19#185]
New strains of the virus are emerging which have different properties. In particular, a new strain in the UK is 1.4-1.7 times more transmissible than the regular strain. As yet, there is no evidence that this strain has different symptoms/outcomes than the original strain. It is also believed to confer cross-immunity with the original strain and vice versa.

Add a strain transmissibility factor which is inherited when someone is infected and the ability to seed a new strain in the middle of a simulation.

**Comment by ewan-wakeman** [comment]
This would be really helpful 👍🏻 

Assume we'd either set points in which to *re-seed* the model with the new strain (i.e similarly to how we originally seed model) or *select* a transmission on a given day to mutate into new strain. Do you have a preference for which one would make sense? From our perspective as we run a series of simulations within separate geographies it may make sense to assume the mutation is a "re-seed" as at least in some cases it will occur as the result of a transmission from another area not seen by the simulation. I imagine this would also hold for any other new strains of the virus (i.e. they develop outside of model populations in most cases rather than within it).

This also raises an interesting question in terms of how we might use this in calibration in the future. We could wither assume we know relative R<sub>0</sub> and use this to model likely proportions in population, or potentially use estimates of prevalence from testing data (assuming these are accessible) and attempt to calibrate these to find a suitable parameter value for the R<sub>0</sub> relative to the first strain. The latter I think would take a bit more work at our end, but worth considering as an approach.

Do you have any thoughts as to what would make the most sense?

**Comment by roberthinch** [comment]
I agree that a re-seed of additional cases with a new strain(s) makes more sense than a mutation for the reasons that you give.

Given that the model is was calibrated, it probably makes sense to freeze all the parameters from the calibration with the base strain and then add the new strain on top.

**Comment by ewan-wakeman** [comment]
This makes sense. In terms of calibration then would you foresee that we'd keep `mean_infectious_rate` and `mean infectious_period` as and keep our `relative_transmission_strength_...` parameters as per recent calibrations (say up to around Nov lockdown for London/SE) and then use second strain with a second set of `relative_transmission_strength_...` parameters to *explain the difference* in essence? So we'd essentially assume any divergence from curves that would be produced based on old transmission strengths with NPIs can be thought of as occurring as a result of the new strain and therefore floating a *set of/single* parameter(s) to capture the `relative_transmission_...` of the new strain would begin to give us a good read on what this would need to be in the model.

Only issue I can see is perhaps a conflation of transmission strength changes based on changes in behavior over Christmas (i.e. any given contact likely to yield more infection as predominantly inside and likely between family/friends) which is happening at a similar time to new train emerging. That said, as the new strain emerged at different points in different parts of the country, there's probably something that can be done to help tease out these separate effects from one another.
