### ISSUE TITLE
What is the purpose of the calibration?

### ISSUE THREAD

**Issue by eidelen** [BDI-pathogens/OpenABM-Covid19#221]
Hi, 
First of all thank you for making your project available to everybody. 
We are trying to adapt OpenABM for the area of Zürich, Swizterland. We [adjusted](https://github.com/armasuissewt/OpenABM-Covid19/blob/d026e998ce8e2ee3c8375f22ffc0855c69e8368f/switzerland/zh/baseline_parameters.csv) many input parameters like population size, population age distribution, and so on. However, we kept your calibrated values for `infectious_rate=5.8` and `sd_infectiousness_multiplier=1.4`. Running a [simple simulation](https://github.com/armasuissewt/OpenABM-Covid19/blob/d026e998ce8e2ee3c8375f22ffc0855c69e8368f/switzerland/ch_zh.py) without countermeasures shows that half of the population is infected after 25 days. That was obviously not the case.
Actually we don't understand how the calibration step exactly works (why doubling time of deaths?). Even more fundamentally, we do not understand the requirement for a calibration in a agent based model. Shouldn't properties like `infectious_rate` be the output of such a simulation?
Best regards,
Adrian

**Comment by roberthinch** [comment]
The parameter `infectious_rate` is one which should be calibrated to your data. The original value was calibrated to the UK for the pre-March 2020 lockdown and should give a doubling time of about 3 days (leading to half the population infected on day 25 in your runs). Clearly there have been many measures put in place since then which lower R and should be included before calibrating `infectious_rate`, such as social distancing measures (e.g. set `relative_transmission_occupation` and `relative_transmission_random` to about 0.7) and self-isolation upon symptoms (`self_quarantine_fraction`=0.7). There will also be immunity built from vaccinations (look at the examples) and natural immunity from infection. The parameter `sd_infectiousness_multiplier=1.4` is related to super-spreading and is calibrated to give a k=0.5 with the original set of parameters, so probably should not be changed.
