### ISSUE TITLE
Allow manipulation of infection dynamics

### ISSUE THREAD

**Issue by aaron-scheffler** [BDI-pathogens/OpenABM-Covid19#45]
A useful enhancement would be to allow adjustments of infection dynamics while the simulation is running. For example, behavioral changes manifested at the societal level (social distancing, hand washing, mask wearing, etc...) may affect the underlying infectious rate or relative transmission dynamics. A secondary feature would be to group people into those who are behaving responsibly and those who do not (i.e. adjust the infectious_rate only for a fraction of the population which could be tuned to model population level compliance.). I still see lots of people without masks. Cheers!

**Comment by brynmathias** [comment]
I'll let @roberthinch or @p-robot comment on this one.

The change is fairly easy to make, but tracking the state through the out the time series will require some more work.

**Comment by roberthinch** [comment]
Yes, adjusting the infection dynamics via the strength of transmissions in pairwise interactions makes most sense. Given that this is likely to be unchanged at home, it makes most sense to do this at the level of networks (i.e. dynamically reduce on work/random networks due to model social distancing). I have code to do this on my private fork, but will need to write some tests before adding it to the main code base.

**Comment by roberthinch** [comment]
The ability to change the relative transmission rate by network type was added in PR #62 .

Here are the Python commands that all you to change them mid run (no change for the household from baseline, a 25% reduction in transmission rates for occupation and random networks).

```
model.update_running_params( "relative_transmission_household",  2 )
model.update_running_params( "relative_transmission_occupation", 0.75 )
model.update_running_params( "relative_transmission_random",  0.75 )
```

**Comment by aaron-scheffler** [comment]
Great, thank you very much!
