### ISSUE TITLE
Spike in daily incidents when setting lockdown off

### ISSUE THREAD

**Issue by dearliory** [BDI-pathogens/OpenABM-Covid19#52]
Hi, 

I would like reproduce the result shown in Fig 3 baseline of NHSX Report
(https://github.com/BDI-pathogens/covid-19_instant_tracing/blob/master/Report%20-%20Effective%20Configurations%20of%20a%20Digital%20Contact%20Tracing%20App.pdf)
 
What I did is to turn the lockdown_on parameter on at day 0 and off at day 35 with n_total = 100000.
sim.env.model.update_running_params("lockdown_on", 1) # at day 0
sim.env.model.update_running_params("lockdown_on", 0) # at day 35

The output I get contains a spike right after the lockdown is set off. This is different from Fig 3 (baseline) in the NHSX report. Can you please check what is going wrong and how to reproduce the result in the report? 

[pasted image 0.pdf](https://github.com/BDI-pathogens/OpenABM-Covid19/files/4630584/pasted.image.0.pdf)

**Comment by roberthinch** [comment]
The baseline scenario in the report contains people (and their households) quarantining upon symptoms, which is/was UK guidelines. Adding this the spike disappears, here is a run with 500k people, code at the bottom.

![new_infected_with_self_isolate](https://user-images.githubusercontent.com/17180566/82044253-ed676280-96a4-11ea-83c8-5aac6cc901f3.png).

As for why there can be a spike on the day after lockdown. This is because a large part of people's interaction networks are recursive (i.e. you see the same people at work each day). Therefore, the number of people you meet in day 2 and can infect is less than on day 1 since a small proportion of them have already been infected on day 1. Note, that the people who became newly infected on day 1 post lockdown will only be very slightly infectious on day 2. As the infectiousness of these newly infected people increases over the next 2-6 days you get the rapid the increase in new infections.

One other thing, I think stochasticity has made the spike on your run more pronounced by chance. If I run on 500,000 people, the spike, whilst still existing is relatively smaller (see below). Note, the results in the paper are from super-imposing 65 runs each of 1m people (with a synchronised start of the lockdown based on the number of infected people).

![new_infected_without_self_isolate_500k](https://user-images.githubusercontent.com/17180566/82044332-138d0280-96a5-11ea-8214-06a0f12eb40f.png)


Code to generate top plot.
```
import example_utils as utils
import pandas as pd

n = 5e5
params = utils.get_baseline_parameters()
params.set_param( "n_total", n )
sim = utils.get_simulation( params )
sim.steps(1)
while sim.results["total_infected"][ -1] < (n * 0.01):
    sim.steps(1)
sim.env.model.update_running_params("self_quarantine_fraction", 0.8)
while sim.results["total_infected"][ -1] < (n*0.02):
    sim.steps(1)
sim.env.model.update_running_params("lockdown_on", 1)
sim.steps( 35 )
sim.env.model.update_running_params("lockdown_on", 0)
sim.steps(50)

timeseries = pd.DataFrame( sim.results )
timeseries[ "new_infected"] = timeseries["total_infected"] - timeseries["total_infected"].shift(1)
timeseries.plot( x = "time", y = "new_infected" )

```

**Comment by dearliory** [comment]
Thank you very much for the explanation. This really helps.
