### ISSUE TITLE
Can not update quarantine_household_on_traced during running

### ISSUE THREAD

**Issue by onefork** [BDI-pathogens/OpenABM-Covid19#55]
Hello,

I'm exploring this package.

If I run `example_102.ipynb`, it always stops with this error `ModelParameterException: Can not update quarantine_household_on_traced during running`. Is there a problem with my setup (Ubuntu 18.04 + conda + swig 3.0 on Window 10 WSL)?

Thank you!
Best
Bin

**Comment by roberthinch** [comment]
Thank you for pointing this out, the example has not been updated since we split out `quarantine_household_on_traced` to depend on whether the trace is from a confirmed positive case or not. If you replace it with `quarantine_household_on_traced_on_symptoms` the example will work. I will put in a PR to fix now.
